[package]
name = "fiber"
version = "0.7.2"
edition = "2021"
authors = ["Chainbound <admin@chainbound.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# types & decoding
alloy-rpc-engine-types = { git = "https://github.com/alloy-rs/alloy", features = [
    "ssz",
], rev = "e127fed" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", features = [
    "ssz",
], rev = "e127fed" }
alloy-rlp = { git = "https://github.com/alloy-rs/rlp" }
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.4", default-features = false, features = [
    "c-kzg",
] }
serde = { version = "1.0", features = ["derive", "rc"] }
ethereum_ssz = "0.5.3"
base64 = "0.13.1"
serde_json = "1.0"
serde_repr = "0.1"
hex = "0.4.3"

# grpc
tonic = { version = "0.10", features = ["gzip", "prost"] }
prost = "0.12"

# runtime
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
async-stream = "0.3"
pin-project = "1"

# metrics
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-build = "0.10"
