[package]
name = "fiber"
version = "0.7.4"
edition = "2021"
license = "MIT"
authors = ["Chainbound <admin@chainbound.io>"]

[dependencies]
# alloy
alloy-rpc-types-engine = { version = "0.1.3", features = ["ssz"] }
alloy-rpc-types = { version = "0.1.3", features = ["ssz"] }
alloy-rlp = "0.3"

# reth
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.0", default-features = false, features = ["std", "c-kzg"] }

# ethereum
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "cf3c404" }
ethereum_ssz = "0.5.3"

# serialization
serde = { version = "1.0", features = ["derive", "rc"] }
base64 = "0.13.1"
serde_json = "1.0"
serde_repr = "0.1"
hex = "0.4.3"

# grpc
tonic = { version = "0.10", features = ["gzip", "prost"] }
prost = "0.12"

# runtime
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
async-stream = "0.3"
pin-project = "1"

# metrics
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-build = "0.10"
