[package]
name = "fiber"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.0"
tonic = "0.8"
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
ethers = "2"
tokio-stream = "0.1.9"
async-stream = "0.3.3"
futures-core = "0.3.24"
futures-util = "0.3.24"
pin-project = "1.0.12"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1"
base64 = "0.13.1"
hex = "0.4.3"
chrono = "0.4.23"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-build = "0.8"
