[package]
name = "fiber"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3"
base64 = "0.13.1"
hex = "0.4.3"
pin-project = "1"
prost = "0.12"
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v0.1.0-alpha.17" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1"
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
tonic = { version = "0.10", features = ["gzip", "prost"] }
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-build = "0.10"
